apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: leonardoloor/php-apache-matricula:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: "pgsql:host=postgres;port=5433;dbname=sistema_matricula;user=postgres;password=admin123"
