apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: NodePort
  selector:
    app: php-app  # Asegúrate de que este selector coincida con las etiquetas del pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
