version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: leonardoloor/php-apache-matricula
    ports:
      - "8082:80" # Mapea el puerto 80 del contenedor al puerto 8082 del host
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5433/sistema_matricula
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sistema_matricula
    ports:
      - "5433:5432" # Cambia el puerto en el host a 5433 si lo deseas
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/sistema_matricula.sql:/docker-entrypoint-initdb.d/sistema_matricula.sql # Monta el archivo SQL para inicialización

volumes:
  postgres_data:
